### ISSUE TITLE
Change slice notation

### ISSUE THREAD

**Issue by jim22k** [jim22k/grblas#2]
The slice notation used by grblas for updating an existing object is awkward.  For example,
```python
C[Q, BinaryOp.PLUS, REPLACE] = A.mxm(B, Semiring.MIN_PLUS)
```
The system can figure out that `Q` is of type Matrix, so it must be the mask, but Python's bracket notation doesn't allow keywords. It would be much clearer if this could be spelled as:
```python
C[mask=Q, accum=BinaryOp.PLUS, replace=True] = A.mxm(B, Semiring.MIN_PLUS)
```

## Proposal for new notation [EDIT: this is outdated; scroll to comment on 3/11 for new proposal]
In order to have keyword arguments, we need a function or method.

The current separation of arguments which affect the output (mask, accumulator, replace) is a nice feature because it segments the different concepts, making the whole GraphBLAS API easier to digest.

We already have `.new(dtype=..., mask=...)` for delayed objects. Because these objects are always new, the concepts of mask and replace don't apply.

We will extend this concept by having an `out.update(obj, mask=..., accum=..., replace=False)` method. Here is how it will look:
```python
C.update(A.mxm(B, Semiring.MIN_PLUS), mask=Q, accum=BinaryOp.PLUS, replace=True)

# Alternative whitespace view for clarity
C.update(A.mxm(B, Semiring.MIN_PLUS),
         mask=Q, accum=BinaryOp.PLUS, replace=True)
```

This keeps the separation, while allowing for keywords to be used for extra clarity.

The usage of A.T and ~Q for descriptor bits will still be used, as this keeps information as close to the affected object as possible.

## New usage of slice syntax
The slice syntax still makes sense for `extract` and `assign`. Rather than making these methods, we will use slice syntax and merge the various dimensional cases.

For `extract`, GraphBLAS makes a distinction between extracting a matrix or a vector (GrB_extract), and a scalar (GrB_Matrix_extractElement). We will not make a distinction in the grblas grammar, but can easily dispatch to the correct GraphBLAS function.
```python
C.update(A[rows, cols])  # extract a matrix
w.update(A[rows, col_index])  # extract a vector
s.update(A[row_index, col_index])  # extract a scalar
```

`assign` will similarly combine the updating of many elements or a single element. Because the rows and columns apply to the output, not the input, we want the brackets to hang off the output. The only way to make this work in Python is to have the `update` method come after the slice brackets. This actually reads quite well, as those positions are the ones being updated.
```python
C[rows, cols].update(A)
C[rows, col_index].update(v)
C[row_index, col_index].update(s)
C[rows, cols].update(s)
```
Notice the common notation of the last two examples, both of which use a scalar to update a matrix. One updates a single element of the matrix. The other updates many elements with the same value. In GraphBLAS, these are very different calls, but in our notation they look identical.

### Methods on slices
Calling `C[rows, cols]` creates a delayed object. It is not clear yet whether the user wants to extract these elements or update them. Fortunately, subsequent calls make it very clear the intended usage.
```python
C[rows, cols].update(A)  # update makes it clear these are being assigned
C.update(A[rows, cols])  # being passed to update makes it clear these are being extracted from A
A[rows, cols].new()  # new makes it clear these are being extracted from A into a new object
```

### Other thoughts
Initially, the plan was to use a proper __setitem__ for assign, like this:
```python
C[rows, cols] = A
```
However, this doesn't leave any place to indicate the mask or accumulator, so we should go with `.update` instead.

**Comment by eriknw** [comment]
Note that these can be handled as expected:
```python
C[row]  # to assign or extract a full row vector; equivalent to `C[row, :]`
C[:, col]  # to assign or extract a full column vector
C[rows, :]  # to assign or extract a matrix (all columns)
C[:, cols]  # to assign or extract a matrix (all rows)
```
- Should we allow `C[rows]` to be equivalent to `C[rows, :]`?
- Should `C[row] be equivalent to `C[row, :]`?
- How should we handle `C[:, :]`, `C[:]`, and `x[:]`?
- Should we handle `del C[rows, cols]` (and variants)?

Will anything change for reductions with the proposed syntax?

**Comment by jim22k** [comment]
```python
C[rows, :]
C[:, cols]
C[:, :]
v[:]
```
These are definitely allowed. They directly map to the GrB_ALL constant.

`del C[rows, cols]` will be the correct syntax for GrB_deleteElement, once SuiteSparse updates to spec v1.3. Deleting wasn't part of 1.2.

As for `C[rows]` being equivalent to `C[rows, :]`, I'm a slight -1 at the moment. I like being more explicit, especially if the variable names aren't clear whether we have a vector or a matrix. `some_var[5]` tells me instantly that I have a vector, while `some_var[5, col_list]` tells me I'm dealing with a matrix.

**Comment by jim22k** [comment]
Okay, somewhat new approach on this, which I came to after rewriting some tests and not liking the separation of output kwargs from the variable they affect. i.e. I don't like this:
```python
C.update(A.mxm(B, Semiring.MIN_PLUS), mask=Q, replace=True)

# This is better, but still separated
C.update(A.mxm(B, Semiring.MIN_PLUS), 
         mask=Q, replace=True)
```

## New _new_ proposal
My new proposal is that grblas objects should have a `__call__` method which returns an `Updater` object. The `Updater` object has an `.update()` method on it. So the previous statement would look like:
```python
C(mask=Q, replace=True).update(A.mxm(B, Semiring.MIN_PLUS))
```

Because it's still a function call, keyword-arguments are allowed for clarity. They are not required for masks and accumulators, but a keyword is required for `replace`.
```python
delayed = A.mxm(B, Semiring.MIN_PLUS)

# The following are all allowed
C(mask=Q, accum=BinaryOp.PLUS, replace=True).update(delayed)
C(Q, BinaryOp.PLUS, replace=True).update(delayed)
C(BinaryOp.PLUS, Q, replace=True).update(delayed)
C(Q).update(delayed)
C(BinaryOp.PLUS).update(delayed)
C(accum=BinaryOp.PLUS).update(delayed)
etc.
```

The signature for call is 
```python
def __call__(self, param1, param2, *, mask=None, accum=None, replace=False)
```
This allows us to pass in the mask and accumulator in whatever order desired and use keywords when desired. We can always figure out based on context.

Recommendation to users would be to use keywords when the variable name isn't descriptive.  For example:
```python
# This is clear from the variable name that it's a mask
C(working_mask).update(delayed)

# In this case, better to use a keyword
C(mask=~C).update(delayed)
# because this is somewhat confusing at first glance
C(~C).update(delayed)
```

## `<<` sugar for updates
As a convenience option, we can use `<<` as syntactic sugar for the `.update()` method.
```python
C(mask=Q) << A.mxm(B, Semiring.MIN_PLUS)
v(BinaryOp.PLUS) << C.reduce(BinaryOp.MAX)
D(mask=D) << D.mxm(D.T)
```

## Update with no extra options
Often, the update happens without an accumulator, mask, or replace. Requiring the user to call `C().update(delayed)` seems unreasonable.

We will provide a `.update()` method directly on the object which behaves the same as if a no-arg call were made on the object. So we can just use `C.update(delayed)`.

Similarly, the use of `<<` will work. For example, `C << delayed` will update C with no mask, no accumulator, and replace=False.

## Quirks with assign
Previously, assign used `C[rows, cols].update(delayed, mask, accum)`. By pushing output arguments closer to the output, we now have congestion in that area.
```python
# Option 1
C[rows, cols](mask) << A
# Option 2
C(mask)[rows, cols] << A
# Simple case
C[rows, cols] << A
```

Additionally, because `__setitem__` satisfies our needs and is Pythonic, we could also write:
```python
# Option 2 from above
C(mask)[rows, cols] = A
# Simple case from above
C[rows, cols] = A
# Option 1 from above will FAIL
C[rows, cols](mask) = A  # NOT ALLOWED by Python syntax parser
```

Because neither order of `C(kwargs)[rows, cols]` or `C[rows, cols](kwargs)` feels more or less natural, we should support both styles.

Because `__setitem__` notation is so common in Python, we should definitely support it for the cases where it is valid Python.

**Comment by eriknw** [comment]
All of this looks good to me. 

Some clarifications and questions:
1. `<<` is an expression.  Until there is a compelling argument, let's have the expression return `None` to disallow chaining such as `D << A.mxm(B) << D.mxm(C)`
2. Can `C()` be used to create an updater?
3. Shouldn't the signature for `__call__` be something like:
```python
def __call__(self, *optional_mask_and_accum, *, mask=None, accum=None, replace=False):
```
4. Given `delayed` as a delayed expression, what's the signature of `delayed.new`?
  a. Can one do `delayed.new(dtype='int64', mask=M)`?

**Comment by jim22k** [comment]
1. Agree on `<<` returning `None`
2. Yes, `C()` can be used to create an updater, but is not required, so these both work
  - `C << delayed`
  - `C.update(delayed)`
3. Yes, that is a better signature than what I proposed
4. `delayed.new` signature is the same as before, with both a dtype and mask argument available

**Comment by eriknw** [comment]
Let's make it happen!

**Comment by jim22k** [comment]
I've run into difficulties with `extractElement` and `assignElement`.

Someone is going to want to do `A[0, 0] + 2` and expect it to work.

Someone else is going to want to write `A[0, 0](accum=BinaryOp.PLUS) << 2` and expect it to work.

There is no way to make Python happy in both cases. Python see a `__getitem__` on `A`. It has no idea whether to execute immediately or delay in case someone is using masked assignment with `<<`.

## Approach 1
We bring back `A.element[]` notation, giving the user an explicit way to indicate immediate execution mode for single elements.
```python
A.element[0, 0]  # returns 5
A.element[0, 0] = 12  # assign a scalar
del A.element[0, 0]  # delete a scalar
```
Then, when single elements are used in regular slice notation, it gets converted to the fully generic case.
```python
C[0, 0](accum=BinaryOp.PLUS) << 5
# The above works because it gets translated to
C[[0], [0]](accum=BinaryOp.PLUS) << 5
```

## Approach 2
We instantly resolve single-element slices depending on whether `__getitem__`, `__setitem__`, or `__delitem__` was called.
```python
A[0, 0]  # instantly resolves
A[0, 0] = 5  # this still works
del A[0, 0]  # this works

# This will likely confuse users
A[0, 0] << 5  # this will return something strange because it's equivalent to `5 << 5`
```
Because of this potential confusion, going with this option only makes sense if we also use the following restrictions:

  - Output args must precede assignment brackets
  - Assignment must be done with `=`, not `<<`
```python
A[rows, cols](mask) << 5 # NOT ALLOWED
A(mask)[rows, cols] = 5 # this is correct
```

## Approach 3
Restrict element-wise access to the following:
```python
A[0, 0].value  # must call .value to cause it to execute
A[0, 0] = 5  # no use of << or any output params allowed
del A[0, 0]
```
All other usages of slicing will be converted to non-single-element calls.

**Comment by eriknw** [comment]
I don't particularly like any of these approaches.

Why not keep the original plan and then have `A[0, 0] + 2` raise?  The error message may even be nice enough to say to use `.new()`, since the preferred expression will be `A[0, 0].new() + 2`.  This keep scalars consistent with vectors and matrices.

Currently, `grblas` scalars are not Python scalars.  It shouldn't be surprising to need to do `.new()` when you want a real object.  Do you want to get rid of `grblas` scalars?

Relatedly, having a `.value` property on a `grblas` scalar that returns a Python type (if possible) may be convenient.  `c.value` to use it, `c.value = 7` to set it.  This gives us many ways to change the value of a scalar, including `c.update(7)` and `c << 7`, which, admittedly, don't feel as natural for scalars.

With `.value`, we now have two preferred variants depending on what you want:
1. `A[0, 0].value + 2` if you want a Python object
2. `A[0, 0].new() + 2` if you want a `grblas` scalar.

It's late, so I'm unsure about `A[0, 0].value = 7`.  The property getter of this (`A[0, 0].value`) clearly returns a Python scalar given the above conventions.  But, should the property setter allow you to do `A[0, 0].value = 7`?  Feels like `A[0, 0] = 7`, `A[0, 0] << 7`, or `A[0, 0].update(7)` are preferred.  

So, coming full circle, if you do
```
c = A[0, 0]
d = c + 2
```
which *looks* fine, because you think `c` is a scalar of some kind, then I think it's okay to raise for `c + 2` and tell the user to use `.new()` or `.value`.  We probably shouldn't try to coerce `c` into behaving like a `grblas` scalar, because then what does this do?
```
c = A[0, 0]
c.value = 5
```
If you think `c` is normal a scalar, then you (and future readers of code) will be very surprised that `A[0, 0]` is updated!  Hence, this is also why we should probably raise on `A[0, 0].value = 7`.

**Comment by jim22k** [comment]
I agree with you. `A[0, 0].value` makes it clear users want the Python scalar, while `A[0, 0].new()` will return a grblas.Scalar.

Assigning to `.value` is dangerous, so we'll disallow that.

Implementation will be more complex, but it hopefully make a simpler experience for users. In essence, the `extractElement` and `assignElement` becomes a fast-path in cases where it applies, but still have a slow path for the more general usages.
